import { AppShell } from "@/components/app-shell/app-shell";
import { Card } from "@/components/ui/card";
import { SimpleTable } from "@/components/tables/simple-table";
import { getCategoryCarryover } from "@/lib/calculations/category-carryover";
import { formatWholeMoney } from "@/lib/money";
import { createTransactionAction, deleteTransactionAction } from "@/app/actions";
import { getBudgetData } from "@/lib/services/budget-data-service";

export const dynamic = "force-dynamic";

export default async function SpendingPage() {
  const { categories, transactions } = await getBudgetData();
  const carryovers = getCategoryCarryover(categories, transactions, "2026-07");
  return <AppShell><div className="grid gap-5 xl:grid-cols-[0.85fr_1.15fr]"><Card><h1 className="font-display text-5xl">Quick Add</h1><form action={createTransactionAction} className="mt-5 grid gap-3"><input type="date" name="date" defaultValue="2026-07-18" className="rounded-xl border border-white/15 bg-black/20 px-4 py-3" /><input name="merchant" className="rounded-xl border border-white/15 bg-black/20 px-4 py-3" placeholder="Merchant" /><input name="amount" className="rounded-xl border border-white/15 bg-black/20 px-4 py-3" placeholder="Amount" /><select name="categoryId" className="rounded-xl border border-white/15 bg-black/20 px-4 py-3">{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><select name="cashFlowTreatment" className="rounded-xl border border-white/15 bg-black/20 px-4 py-3"><option value="CASH_DEBIT">Cash/debit</option><option value="CREDIT_CARD">Credit card</option></select><select name="plannedStatus" className="rounded-xl border border-white/15 bg-black/20 px-4 py-3"><option value="UNPLANNED">Unplanned</option><option value="PLANNED">Planned</option></select><label className="flex items-center gap-2 text-sm"><input name="isReimbursable" type="checkbox" /> Reimbursable</label><textarea name="notes" className="rounded-xl border border-white/15 bg-black/20 px-4 py-3" placeholder="Notes" /><button className="rounded-xl bg-ledger-amber px-4 py-3 font-bold text-ledger-ink">Add transaction</button></form></Card><Card><h2 className="font-display text-3xl">Category carryover</h2><div className="mt-5"><SimpleTable headers={["Category", "Base", "Available", "Spent", "Remaining", "Alert"]} rows={carryovers.map((item) => [item.category.name, formatWholeMoney(item.category.baseMonthlyBudgetCents), formatWholeMoney(item.availableBudgetCents), formatWholeMoney(item.actualSpentCents), formatWholeMoney(item.remainingCents), item.isWarning ? "80% reached" : ""])} /></div></Card></div><Card className="mt-5"><h2 className="font-display text-3xl">Transactions</h2><div className="mt-5"><SimpleTable headers={["Date", "Merchant", "Total", "Treatment", "Splits", "Receipt", "Delete"]} rows={transactions.map((tx) => [tx.date, tx.merchant, formatWholeMoney(tx.totalAmountCents), tx.cashFlowTreatment, tx.splits.length, tx.receiptFileName ?? "", <form key={tx.id} action={deleteTransactionAction}><input type="hidden" name="id" value={tx.id} /><button className="rounded-lg border border-ledger-rose/50 px-3 py-1 text-red-100">Delete</button></form>])} /></div></Card></AppShell>;
}
